apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: {{ istio_namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
spec:
  backend:
    serviceName: kiali
    servicePort: {{ server_port }}
