apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: kiali
  namespace: {{ istio_namespace }}
  labels:
    app: kiali
redirectURIs:
  - ${REDIRECT_URL}
  - localhost:3000
grantMethod: auto
allowAnyScope: true
