apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: kiali
  namespace: {{ namespace }}
  labels:
    app: kiali
redirectURIs:
  - {{ kiali_route }}
  - localhost:3000
grantMethod: auto
allowAnyScope: true
