apiVersion: v1
kind: Route
metadata:
  name: kiali
  namespace: {{ namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
spec:
  tls:
    termination: reencrypt
  to:
    kind: Service
    targetPort: {{ server_port }}
    name: kiali
