apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: {{ namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
type: Opaque
data:
  username: {{ kiali_username_base64 }}
  passphrase: {{ kiali_passphrase_base64 }}
