apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: {{ istio_namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
type: Opaque
data:
  username: {{ kiali_username | b64encode}}
  passphrase: {{ kiali_passphrase | b64encode}}
