apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: kiali-cert-secret
  name: kiali
  namespace: {{ istio_namespace }}
  labels:
    app: kiali
    version: {{ version_label }}
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 20001
  selector:
    app: kiali
    version: {{ version_label }}
