- name: Detect Jaeger Route
  k8s_facts:
    api_version: route.openshift.io/v1
    kind: Route
    name: tracing
    namespace: "{{ istio_namespace }}"
  register: jaeger_cluster
  when: openshift

- name: Detect Jaeger Route
  set_fact:
    jaeger_url: "http://{{ jaeger_cluster['resources'][0]['status']['ingress'][0]['host'] }}"
  when: openshift