---
- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: 'Set Kiali objects state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: secret.yaml
    - name: configmap.yaml
    - name: serviceaccount.yaml
    - name: clusterrole.yaml
    - name: clusterrolebinding.yaml
    - name: deployment.yaml
    - name: service.yaml
    - name: route.yaml
      api_exists: "{{ True if 'route.openshift.io' in api_groups else False }}"
