- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: "Check if it is openshift"
  set_fact:
    openshift: "{{ True if 'route.openshift.io' in api_groups else False }}"

- name: 'Detect Grafana URL when is not defined'
  include: grafana.yml
  when: grafana_url is not defined

- name: 'Detect Jaeger URL when is not defined'
  include: jaeger.yml
  when: jaeger_url is not defined

- name: 'Set Kiali objects state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name) }}"
  with_items:
  - {name: 'templates/secret.yaml'}
  - {name: 'templates/configmap.yaml'}
  - {name: 'templates/serviceaccount.yaml'}
  - {name: 'templates/clusterrole.yaml'}
  - {name: 'templates/clusterrole-viewer.yaml'}
  - {name: 'templates/service.yaml'}
  - {name: 'templates/clusterrolebinding.yaml'}
  - {name: 'templates/deployment.yaml'}
 

- name: 'Deploy Kiali Route only on openshift'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name)}}"
  when: openshift
  with_items:
  - {name: 'templates/route.yaml'}

