apiVersion: op.kiali.io/v1alpha1
kind: Kiali
metadata:
  name: example-kiali
spec:
  state: present
  auth_strategy: openshift
  kiali_username: 'admin'
  kiali_passphrase: 'admin'
  server_port: 20001
  image_name: kiali/kiali
  image_version: latest
  version_label: latest
  image_pull_policy_token: "imagePullPolicy: Always"
  namespace: istio-system
  istio_namespace: istio-system
  verbose_mode: 3
