---
auth_strategy: openshift
kiali_username: 'admin'
kiali_passphrase: 'admin'
server_port: 20001
image_name: kiali/kiali
image_version: latest
image_pull_policy_token: "imagePullPolicy: Always"
namespace: istio-system
istio_namespace: istio-system
verbose_mode: 3
version_label: latest

state: present
