apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: kiali-operator
subjects:
- kind: ServiceAccount
  name: kiali-operator
  namespace: kiali-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
